---
all:
  hosts:
    switch-sg3210-office:
      ansible_host: 10.0.10.1
      switch_location: "Office"
      port_roles:  # ✅ DIREKT hier!
        management_trunk: 1
        management_access: [2]
        clients: [3, 4, 5, 6]
        guests: [7]
        iot: [8]
        lag: [9, 10]
    
    switch-sg3210-warehouse:
      ansible_host: 10.0.10.2
      switch_location: "Warehouse"
    
    switch-sg3210-lab:
      ansible_host: 10.0.10.3
      switch_location: "Lab"
  
  children:
    managed_switches:
      hosts:
        switch-sg3210-office:
        switch-sg3210-warehouse:
        switch-sg3210-lab:
    
    core_switches:
      hosts:
        switch-sg3210-office:
    
    access_switches:
      hosts:
        switch-sg3210-warehouse:
    
    test_switches:
      hosts:
        switch-sg3210-lab:
